modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory This is typically bumped every Minecraft version by NeoForge. See our download page for lists of versions.
license="GPL 3.0"
issueTrackerURL="https://github.com/aurilisdev/Ballistix" #optional
[[mods]] #mandatory
modId="ballistix" #mandatory
version="0.7.1_bplus-1.0.0" #mandatory
displayName="Ballistix +" #mandatory
displayURL="https://github.com/aurilisdev/Ballistix" #optional
logoFile="ballistix.png" #optional
credits="Thanks to all contributors. Brazil lang file by FITFC. Russian lang file by Quarkrus. Ballistix + by hexagon_inc" #optional
authors="aurilisdev, hexagon_inc" #optional
description=''

[[dependencies.ballistix]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ballistix]]
    modId="electrodynamics"
    mandatory=true
    versionRange="1.21.1-1.0.2"
    ordering="NONE"
    side="BOTH"